// nextPath -related
export const UPDATE_REDIRECT_TO = "UPDATE_REDIRECT_TO";

// login -related
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM";
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM";

// user -related
export const UPDATE_USER = "UPDATE_USER";

// addUserBookForm -related
export const UPDATE_ADD_USERBOOK_FORM_ISBN = "UPDATE_ADD_USERBOOK_FORM_ISBN";
export const UPDATE_ADD_USERBOOK_FORM_BOOKDATA =
  "UPDATE_ADD_USERBOOK_FORM_BOOKDATA";
export const UPDATE_ADD_USERBOOK_FORM_ISBN_CONFIRMATION =
  "UPDATE_ADD_USERBOOK_FORM_ISBN_CONFIRMATION";
export const UPDATE_ADD_USERBOOK_FORM_CONDITION =
  "UPDATE_ADD_USERBOOK_FORM_CONDITION";
export const UPDATE_ADD_USERBOOK_FORM_DESCRIPTION =
  "UPDATE_ADD_USERBOOK_FORM_DESCRIPTION";
export const CLEAR_ADD_USERBOOK_FORM = "CLEAR_ADD_USERBOOK_FORM";

// selectedUserBook -related
export const UPDATE_SELECTED_USERBOOK = "UPDATE_SELECTED_USERBOOK";
export const CLEAR_SELECTED_USERBOOK = "CLEAR_SELECTED_USERBOOK";

// books -related
export const UPDATE_SELECTED_BOOK = "UPDATE_SELECTED_BOOK";
export const CLEAR_SELECTED_BOOK = "CLEAR_SELECTED_BOOK";
export const UPDATE_BOOKS = "UPDATE_BOOKS";
export const CLEAR_BOOKS = "CLEAR_BOOKS";
