// login -related
export const UPDATE_LOGIN_FORM = "UPDATE_LOGIN_FORM";
export const CLEAR_LOGIN_FORM = "CLEAR_LOGIN_FORM";

// user -related
export const UPDATE_USER = "UPDATE_USER";

// addUserBookForm -related
export const UPDATE_ADD_USERBOOK_FORM_ISBN = "UPDATE_ADD_USERBOOK_FORM_ISBN";
export const UPDATE_ADD_USERBOOK_FORM_BOOKDATA =
  "UPDATE_ADD_USERBOOK_FORM_BOOKDATA";
export const UPDATE_ADD_USERBOOK_FORM_ISBN_CONFIRMATION =
  "UPDATE_ADD_USERBOOK_FORM_ISBN_CONFIRMATION";
export const UPDATE_ADD_USERBOOK_FORM_CONDITION =
  "UPDATE_ADD_USERBOOK_FORM_CONDITION";
export const UPDATE_ADD_USERBOOK_FORM_DESCRIPTION =
  "UPDATE_ADD_USERBOOK_FORM_DESCRIPTION";

// activeUserBook -related
export const UPDATE_ACTIVE_USERBOOK = "UPDATE_ACTIVE_USERBOOK";
export const CLEAR_ACTIVE_USERBOOK = "CLEAR_ACTIVE_USERBOOK";
