// user -related
export const UPDATE_USER = "UPDATE_USER";

// addUserBookForm -related
export const UPDATE_ADD_USERBOOK_FORM_ISBN = "UPDATE_ADD_USERBOOK_FORM_ISBN";
export const UPDATE_ADD_USERBOOK_FORM_BOOKDATA = "UPDATE_ADD_USERBOOK_FORM_BOOKDATA";